blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/esp32-si4732/ats-mini/discussions
    about: This is the best place to ask and answer questions, submit feature requests and share ideas/feedback.
