blank_issues_enabled: false
contact_links:
  - name: Ideas, Questions, Show and tell, Feedback
    url: https://github.com/esp32-si4732/ats-mini/discussions
    about: This is the best place to ask and answer questions, submit feature requests and share ideas/feedback.
